rt-doc-type-old.yml

#20 Rename model TFDSIDList -> FDSIDList

---

p-process.yml

- add log into process endpoint definition

rl-26/log Log:

---

rt-text-data.yml
rt-text.yml

- add fieldName definition for document text fields

rl-29/field-name FieldName:

---

p-process.yml

- add forceDocID into processParam definition

rl-31/force-doc-id ForceDocID:

---

.github/workflows/update-clients.yml

- add ability to run update-models.sh without DOCS_DEFINITION_FOLDER environment

rl-492/openapi-generator OpenapiGenerator:

---

rt-doc-type-old.yml

* FDSIDList.ICAO renamed to FDSIDList.ICAOCode
* minLength and maxLength changed to 3

FDSIDList.ICAOCode fix

---

p-process.yml

- add process params for b5.4 release: matchTextFieldMask, fastDocDetect, updateOCRValidityByGlare, generateDoublePageSpreadImage, checkRequiredTextFields

rl-519/v5.4 v5.4:

---

e-text-field-type.yml

https://redmine.regulaforensics.com/issues/29346
- ft_Second_Name = 647
- ft_Third_Name = 648
- ft_Fourth_Name = 649
- ft_Last_Name = 650

[29346] Add 647-650 name types

---

common.yml
index.yml
p-process.yml

processParams: { ImageQA { glaresCheckParams: {imgMarginPart: 0.35, maxGlaringPart: 0.0} } }
processParams: { splitNames: true }
processParams { disablePerforationOCR: true}
processParams { processAuth: true }
processParams { documentGroupFilter: "242"}
processParams { respectImageQuality: true}

6.3 update 

---

common.yml
index.yml
p-process.yml

processParams: { ImageQA { glaresCheckParams: {imgMarginPart: 0.35, maxGlaringPart: 0.0} } }
processParams: { splitNames: true }
processParams { disablePerforationOCR: true}
processParams { processAuth: true }
processParams { documentGroupFilter: [enum:DoumentType]}
processParams { respectImageQuality: true}

6.3 update

---

authenticity/e-check-diagnose.yml

In **e-check-diagnose.yml**:
- WORNG_MRZ_DPI = 200
- WRONG_BACKGROUND = 201

[30996] Update eCheckDiagnose

---

e-text-field-type.yml

- Payment_Period_From = 642
- Payment_Period_To = 643
- VaccinationCertificateIdentifier = 644
- First_Name = 645
- Date_of_Arrival = 646,

[SP-2763] Update TextFieldType

---

p-process.yml

[SP-3957] Add documentIdList

---

p-process.yml

https://app.clickup.com/t/4535044/SP-11933

SP-11933: Issue with processing the document

---

p-process.yml

https://app.clickup.com/t/4535044/SP-12990

SP-12990: Add checkLiveness field to Process Params

---

p-process.yml

https://app.clickup.com/t/4535044/SP-12947

SP-12947: Add lcidFilter to process params

---

p-process.yml

https://app.clickup.com/t/4535044/SP-13192

SP-13192: Mark doublePageSpread as deprecated

---

p-process.yml

https://app.clickup.com/t/4535044/SP-13436

SP-13436: Mark fastDocDetect as deprecated

---

authenticity/e-check-diagnose.yml
e-graphic-field-type.yml
e-security-feature-type.yml
e-text-field-type.yml

https://app.clickup.com/t/4535044/SP-12972

SP-12972: Add new constants

---

authenticity/e-check-diagnose.yml
e-text-field-type.yml

https://app.clickup.com/t/8693ub8t6
https://app.clickup.com/t/4535044/SP-13634

SP-13638: Add new constants

---

p-process.yml

It works only in the process series

SP-14693: Removed documentAreaMin

---

p-transaction.yml

SP-15220: Correct transaction process request

---

index.yml
p-transaction.yml

SP-16044: Add get transactions by tag endpoint

---

p-process.yml
rt-image-quality.yml

Use Document Liveness in Authenticity instead

Removed Screen Capture from Image Quliaty

---

p-process.yml

Reverts regulaforensics/DocumentReader-web-openapi#182

Revert "Added authOneThreadProcessing"

---

p-transaction.yml

SP-19158: Add dtc to reprocess

---

p-process.yml

https://app.clickup.com/t/4535044/SP-20119

SP-20119 mark image data as non required
